<a href="https://colab.research.google.com/github/Amirbn73/Air-pollution-Prediction/blob/main/data_handling_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
from google.colab import files

In [36]:
import pandas as pd

In [ ]:
file = files.upload()

Saving Raw data.csv to Raw data.csv

In [ ]:
df = pd.read_csv('Raw data.csv')

In [ ]:
df.head(10)

,Unnamed: 0,London Bexley,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,London Bloomsbury,...,Unnamed: 55,Unnamed: 56,London Westminster,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Latitude,51.46603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.52229,...,NaN,NaN,51.49467,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Longitude,0.184806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.125889,...,NaN,NaN,-0.131931,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Site Type,Suburban Background,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Urban Background,...,NaN,NaN,Urban Background,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Zone,Greater London,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater London,...,NaN,NaN,Greater London,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Agglomeration,Greater London Urban Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater London Urban Area,...,NaN,NaN,Greater London Urban Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Local Authority,Bexley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Camden,...,NaN,NaN,Westminster,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Date,Ozone,Status,Nitrogen dioxide,Status,Sulphur dioxide,Status,Carbon monoxide,Status,Ozone,...,Carbon monoxide,Status,Ozone,Status,Nitrogen dioxide,Status,Sulphur dioxide,Status,Carbon monoxide,Status
7,01-01-02,6,V ugm-3,65,V ugm-3,5,V ugm-3,1.2,V mgm-3,7,...,1.4,V mgm-3,6,V ugm-3,85,V ugm-3,7,V ugm-3,1.2,V mgm-3
8,02-01-02,5,V ugm-3,57,V ugm-3,21,V ugm-3,0.62,V mgm-3,6,...,0.67,V mgm-3,5,V ugm-3,74,V ugm-3,6,V ugm-3,0.66,V mgm-3
9,03-01-02,7,V ugm-3,57,V ugm-3,32,V ugm-3,0.31,V mgm-3,5,...,0.55,V mgm-3,5,V ugm-3,75,V ugm-3,15,V ugm-3,0.61,V mgm-3

In [ ]:
df.tail(30)

,Unnamed: 0,London Bexley,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,London Bloomsbury,...,Unnamed: 55,Unnamed: 56,London Westminster,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
1808,07-12-06,65,V ugm-3,18,V ugm-3,4,V ugm-3,0.15,V mgm-3,46,...,0.46,V mgm-3,60,V ugm-3,30,V ugm-3,1,V ugm-3,0.14,V mgm-3
1809,08-12-06,22,V ugm-3,57,V ugm-3,5,V ugm-3,0.39,V mgm-3,15,...,0.65,V mgm-3,22,V ugm-3,58,V ugm-3,5,V ugm-3,0.35,V mgm-3
1810,09-12-06,12,V ugm-3,52,V ugm-3,3,V ugm-3,0.42,V mgm-3,4,...,0.4,V mgm-3,8,V ugm-3,64,V ugm-3,4,V ugm-3,0.29,V mgm-3
1811,10-12-06,36,V ugm-3,30,V ugm-3,1,V ugm-3,0.25,V mgm-3,22,...,0.37,V mgm-3,30,V ugm-3,44,V ugm-3,1,V ugm-3,0.29,V mgm-3
1812,11-12-06,No data,V ugm-3,43,V ugm-3,2,V ugm-3,0.27,V mgm-3,26,...,0.56,V mgm-3,34,V ugm-3,53,V ugm-3,2,V ugm-3,0.32,V mgm-3
1813,12-12-06,No data,V ugm-3,32,V ugm-3,2,V ugm-3,0.2,V mgm-3,30,...,0.29,V mgm-3,42,V ugm-3,40,V ugm-3,0,V ugm-3,0.2,V mgm-3
1814,13-12-06,No data,V,21,V ugm-3,1,V ugm-3,0.15,V mgm-3,41,...,0.3,V mgm-3,54,V ugm-3,32,V ugm-3,0,V ugm-3,0.13,V mgm-3
1815,14-12-06,No data,V,17,V ugm-3,2,V ugm-3,0.14,V mgm-3,46,...,0.18,V mgm-3,60,V ugm-3,29,V ugm-3,1,V ugm-3,0.11,V mgm-3
1816,15-12-06,No data,V,26,V ugm-3,0,V ugm-3,0.19,V mgm-3,30,...,0.29,V mgm-3,46,V ugm-3,36,V ugm-3,2,V ugm-3,0.17,V mgm-3
1817,16-12-06,No data,V,48,V ugm-3,1,V ugm-3,0.33,V mgm-3,12,...,0.65,V mgm-3,16,V ugm-3,60,V ugm-3,5,V ugm-3,0.34,V mgm-3
1818,17-12-06,No data,V,50,V ugm-3,2,V ugm-3,0.52,V mgm-3,9,...,0.5,V mgm-3,14,V ugm-3,60,V ugm-3,4,V ugm-3,0.41,V mgm-3
1819,18-12-06,No data,V,65,V ugm-3,11,V ugm-3,0.97,V mgm-3,2,...,0.86,V mgm-3,3,V ugm-3,75,V ugm-3,13,V ugm-3,0.55,V mgm-3
1820,19-12-06,No data,V,79,V ugm-3,7,V ugm-3,0.89,V mgm-3,3,...,0.91,V mgm-3,4,V ugm-3,86,V ugm-3,17,V ugm-3,0.92,V mgm-3
1821,20-12-06,1,V,99,V ugm-3,8,V ugm-3,1.2,V mgm-3,4,...,1.2,V mgm-3,4,V ugm-3,81,V ugm-3,16,V ugm-3,0.89,V mgm-3
1822,21-12-06,0,V ugm-3,80,V ugm-3,13,V ugm-3,0.98,V mgm-3,3,...,1,V mgm-3,4,V ugm-3,76,V ugm-3,24,V ugm-3,0.8,V mgm-3
1823,22-12-06,0,V ugm-3,70,V ugm-3,13,V ugm-3,0.76,V mgm-3,1,...,0.92,V mgm-3,3,V ugm-3,65,V ugm-3,20,V ugm-3,0.87,V mgm-3
1824,23-12-06,11,V ugm-3,41,V ugm-3,6,V ugm-3,0.38,V mgm-3,4,...,0.36,V mgm-3,7,V ugm-3,50,V ugm-3,13,V ugm-3,0.37,V mgm-3
1825,24-12-06,33,V ugm-3,21,V ugm-3,2,V ugm-3,0.15,V mgm-3,20,...,0.23,V mgm-3,23,V ugm-3,37,V ugm-3,5,V ugm-3,0.16,V mgm-3
1826,25-12-06,33,V ugm-3,20,V ugm-3,5,V ugm-3,0.12,V mgm-3,20,...,0.23,V mgm-3,21,V ugm-3,38,V ugm-3,8,V ugm-3,0.14,V mgm-3
1827,26-12-06,8,V ugm-3,40,V ugm-3,10,V ugm-3,0.31,V mgm-3,12,...,0.42,V mgm-3,8,V ugm-3,49,V ugm-3,16,V ugm-3,0.18,V mgm-3
1828,27-12-06,6,V ugm-3,39,V ugm-3,2,V ugm-3,0.42,V mgm-3,4,...,0.57,V mgm-3,6,V ugm-3,43,V ugm-3,9,V ugm-3,0.25,V mgm-3
1829,28-12-06,28,V ugm-3,30,V ugm-3,3,V ugm-3,0.27,V mgm-3,19,...,0.38,V mgm-3,23,V ugm-3,43,V ugm-3,5,V ugm-3,0.22,V mgm-3
1830,29-12-06,40,V ugm-3,20,V ugm-3,4,V ugm-3,0.2,V mgm-3,30,...,0.53,V mgm-3,41,V ugm-3,30,V ugm-3,6,V ugm-3,0.13,V mgm-3
1831,30-12-06,62,V ugm-3,11,V ugm-3,2,V ugm-3,0.14,V mgm-3,48,...,0.4,V mgm-3,58,V ugm-3,No data,V ugm-3,5,V ugm-3,0.12,V mgm-3
1832,31-12-06,64,V ugm-3,10,V ugm-3,3,V ugm-3,0.11,V mgm-3,48,...,0.26,V mgm-3,58,V ugm-3,25,V ugm-3,3,V ugm-3,0.14,V mgm-3
1833,01-01-07,61,V ugm-3,14,V ugm-3,3,V ugm-3,0.16,V mgm-3,41,...,0.24,V mgm-3,48,V ugm-3,No data,V ugm-3,1,V ugm-3,0.23,V mgm-3
1834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1837,End,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ds = df.dropna()

In [ ]:
ds.head()

,Unnamed: 0,London Bexley,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,London Bloomsbury,...,Unnamed: 55,Unnamed: 56,London Westminster,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
6,Date,Ozone,Status,Nitrogen dioxide,Status,Sulphur dioxide,Status,Carbon monoxide,Status,Ozone,...,Carbon monoxide,Status,Ozone,Status,Nitrogen dioxide,Status,Sulphur dioxide,Status,Carbon monoxide,Status
7,01-01-02,6,V ugm-3,65,V ugm-3,5,V ugm-3,1.2,V mgm-3,7,...,1.4,V mgm-3,6,V ugm-3,85,V ugm-3,7,V ugm-3,1.2,V mgm-3
8,02-01-02,5,V ugm-3,57,V ugm-3,21,V ugm-3,0.62,V mgm-3,6,...,0.67,V mgm-3,5,V ugm-3,74,V ugm-3,6,V ugm-3,0.66,V mgm-3
9,03-01-02,7,V ugm-3,57,V ugm-3,32,V ugm-3,0.31,V mgm-3,5,...,0.55,V mgm-3,5,V ugm-3,75,V ugm-3,15,V ugm-3,0.61,V mgm-3
10,04-01-02,5,V ugm-3,54,V ugm-3,7,V ugm-3,0.52,V mgm-3,4,...,0.81,V mgm-3,4,V ugm-3,71,V ugm-3,10,V ugm-3,0.9,V mgm-3

In [ ]:
# df['Unnamed: 2'].str.contains('V ugm-3').any()

In [ ]:
for i in ds.columns:
  if ds[i].str.contains('V ugm-3').any() or ds[i].str.contains('V mgm-3').any():
    ds.drop(columns = i, inplace = True)

ds.head(20)

<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)
<ipython-input-10-d75f2166f75c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns = i, inplace = True)

,Unnamed: 0,London Bexley,Unnamed: 3,Unnamed: 5,Unnamed: 7,London Bloomsbury,Unnamed: 11,Unnamed: 13,Unnamed: 15,London Brent,...,Unnamed: 45,Unnamed: 47,London Southwark,Unnamed: 51,Unnamed: 53,Unnamed: 55,London Westminster,Unnamed: 59,Unnamed: 61,Unnamed: 63
6,Date,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,...,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide
7,01-01-02,6,65,5,1.2,7,62,18,1.1,3,...,13,1.1,4,87,12,1.4,6,85,7,1.2
8,02-01-02,5,57,21,0.62,6,59,13,1.1,4,...,8,0.57,5,70,10,0.67,5,74,6,0.66
9,03-01-02,7,57,32,0.31,5,58,28,0.77,2,...,17,0.4,4,68,20,0.55,5,75,15,0.61
10,04-01-02,5,54,7,0.52,4,56,17,1.1,3,...,10,0.6,4,65,12,0.81,4,71,10,0.9
11,05-01-02,2,50,2,0.65,2,50,9,0.89,2,...,5,0.51,2,59,7,0.82,2,60,3,0.87
12,06-01-02,2,41,6,0.55,2,45,13,0.84,4,...,4,0.55,4,60,4,0.65,2,59,1,0.77
13,07-01-02,2,44,6,0.57,4,51,21,0.7,6,...,6,No data,5,62,10,0.61,4,65,6,0.8
14,08-01-02,4,49,13,0.49,3,50,16,0.82,5,...,11,0.25,3,61,17,0.56,3,67,15,0.67
15,09-01-02,4,60,14,0.66,3,59,14,1.3,2,...,8,0.93,3,66,12,0.98,3,76,10,1.2
16,10-01-02,7,No data,No data,0.64,4,50,8,0.88,5,...,5,0.62,6,62,5,0.72,6,68,3,0.8
17,11-01-02,7,52,7,0.66,3,43,14,0.82,3,...,5,1.1,4,65,9,1,4,72,5,0.99
18,12-01-02,20,33,5,0.62,8,36,6,0.42,14,...,3,0.37,10,54,4,0.63,12,56,4,0.62
19,13-01-02,24,28,4,0.28,11,37,5,0.58,17,...,0,0.3,16,48,2,0.49,17,53,2,0.53
20,14-01-02,25,32,3,0.28,10,41,4,0.62,22,...,1,0.26,17,48,4,0.38,16,54,2,0.51
21,15-01-02,18,55,5,0.32,12,46,18,0.68,18,...,2,0.47,15,62,6,0.57,13,72,4,0.66
22,16-01-02,15,58,5,0.55,5,56,7,0.86,6,...,6,0.52,7,70,7,0.78,9,71,5,0.69
23,17-01-02,34,37,3,0.23,18,46,10,0.68,28,...,3,0.32,26,53,4,0.47,27,57,6,0.49
24,18-01-02,25,40,5,0.66,12,50,9,0.65,20,...,5,0.44,15,62,6,0.75,18,62,6,0.65
25,19-01-02,60,16,3,0.25,34,32,5,0.35,44,...,1,0.14,42,39,3,0.39,42,38,3,0.36

In [ ]:
ds.reset_index(inplace= True)

In [ ]:
ds.head()

,index,Unnamed: 0,London Bexley,Unnamed: 3,Unnamed: 5,Unnamed: 7,London Bloomsbury,Unnamed: 11,Unnamed: 13,Unnamed: 15,...,Unnamed: 45,Unnamed: 47,London Southwark,Unnamed: 51,Unnamed: 53,Unnamed: 55,London Westminster,Unnamed: 59,Unnamed: 61,Unnamed: 63
0,6,Date,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,...,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide
1,7,01-01-02,6,65,5,1.2,7,62,18,1.1,...,13,1.1,4,87,12,1.4,6,85,7,1.2
2,8,02-01-02,5,57,21,0.62,6,59,13,1.1,...,8,0.57,5,70,10,0.67,5,74,6,0.66
3,9,03-01-02,7,57,32,0.31,5,58,28,0.77,...,17,0.4,4,68,20,0.55,5,75,15,0.61
4,10,04-01-02,5,54,7,0.52,4,56,17,1.1,...,10,0.6,4,65,12,0.81,4,71,10,0.9

In [ ]:
ds.drop(columns='index', inplace = True)

<ipython-input-13-ffdaf8889ac8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(columns='index', inplace = True)

In [ ]:
ds.head()

,Unnamed: 0,London Bexley,Unnamed: 3,Unnamed: 5,Unnamed: 7,London Bloomsbury,Unnamed: 11,Unnamed: 13,Unnamed: 15,London Brent,...,Unnamed: 45,Unnamed: 47,London Southwark,Unnamed: 51,Unnamed: 53,Unnamed: 55,London Westminster,Unnamed: 59,Unnamed: 61,Unnamed: 63
0,Date,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,...,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide,Ozone,Nitrogen dioxide,Sulphur dioxide,Carbon monoxide
1,01-01-02,6,65,5,1.2,7,62,18,1.1,3,...,13,1.1,4,87,12,1.4,6,85,7,1.2
2,02-01-02,5,57,21,0.62,6,59,13,1.1,4,...,8,0.57,5,70,10,0.67,5,74,6,0.66
3,03-01-02,7,57,32,0.31,5,58,28,0.77,2,...,17,0.4,4,68,20,0.55,5,75,15,0.61
4,04-01-02,5,54,7,0.52,4,56,17,1.1,3,...,10,0.6,4,65,12,0.81,4,71,10,0.9

In [ ]:
# Assuming df is your initial DataFrame

# Create a new DataFrame with the desired column structure
new_columns = []

# First, add the 'Date' column as is
new_columns.append(('Date', ''))

# Iterate through the columns representing stations and pollutants
station_names = []
pollutant_names = []

for i, column_name in enumerate(ds.columns[1:]):
    if i % 4 == 0:
        station_name = column_name
        station_names.extend([station_name] * 4)
    pollutant_names.extend(list(ds.drop(columns='Unnamed: 0').loc[0]))
    # pollutant_names.extend([pollutant_name] * 4)

new_columns.extend(list(zip(station_names, pollutant_names)))

# # Create the new DataFrame with the modified column structure
# new_df = ds.copy()
ds.columns = pd.MultiIndex.from_tuples(new_columns, names=['Station', 'Pollutant'])

# # Now, you have a new DataFrame with the desired multi-index structure

In [ ]:
ds.head()

Station        Date London Bexley                                     \
Pollutant                   Ozone  Nitrogen dioxide  Sulphur dioxide
0              Date         Ozone  Nitrogen dioxide  Sulphur dioxide
1          01-01-02             6                65                5
2          02-01-02             5                57               21
3          03-01-02             7                57               32
4          04-01-02             5                54                7

Station                    London Bloomsbury                    \
Pollutant  Carbon monoxide             Ozone  Nitrogen dioxide
0          Carbon monoxide             Ozone  Nitrogen dioxide
1                      1.2                 7                62
2                     0.62                 6                59
3                     0.31                 5                58
4                     0.52                 4                56

Station                                     London Brent  ...  \
Pollutant  Sulphur dioxide  Carbon monoxide        Ozone  ...
0          Sulphur dioxide  Carbon monoxide        Ozone  ...
1                       18              1.1            3  ...
2                       13              1.1            4  ...
3                       28             0.77            2  ...
4                       17              1.1            3  ...

Station   London N. Kensington                  London Southwark  \
Pollutant      Sulphur dioxide  Carbon monoxide            Ozone
0              Sulphur dioxide  Carbon monoxide            Ozone
1                           13              1.1                4
2                            8             0.57                5
3                           17              0.4                4
4                           10              0.6                4

Station                                                        \
Pollutant  Nitrogen dioxide  Sulphur dioxide  Carbon monoxide
0          Nitrogen dioxide  Sulphur dioxide  Carbon monoxide
1                        87               12              1.4
2                        70               10             0.67
3                        68               20             0.55
4                        65               12             0.81

Station   London Westminster                                     \
Pollutant              Ozone  Nitrogen dioxide  Sulphur dioxide
0                      Ozone  Nitrogen dioxide  Sulphur dioxide
1                          6                85                7
2                          5                74                6
3                          5                75               15
4                          4                71               10

Station
Pollutant  Carbon monoxide
0          Carbon monoxide
1                      1.2
2                     0.66
3                     0.61
4                      0.9

[5 rows x 33 columns]

In [ ]:
ds.drop(0, inplace = True)

<ipython-input-17-75f10f323b46>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.drop(0, inplace = True)

In [ ]:
ds.head(3)

Station        Date London Bexley                                   \
Pollutant                   Ozone Nitrogen dioxide Sulphur dioxide
1          01-01-02             6               65               5
2          02-01-02             5               57              21
3          03-01-02             7               57              32

Station                   London Bloomsbury                                   \
Pollutant Carbon monoxide             Ozone Nitrogen dioxide Sulphur dioxide
1                     1.2                 7               62              18
2                    0.62                 6               59              13
3                    0.31                 5               58              28

Station                   London Brent  ... London N. Kensington  \
Pollutant Carbon monoxide        Ozone  ...      Sulphur dioxide
1                     1.1            3  ...                   13
2                     1.1            4  ...                    8
3                    0.77            2  ...                   17

Station                   London Southwark                                   \
Pollutant Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
1                     1.1                4               87              12
2                    0.57                5               70              10
3                     0.4                4               68              20

Station                   London Westminster                                   \
Pollutant Carbon monoxide              Ozone Nitrogen dioxide Sulphur dioxide
1                     1.4                  6               85               7
2                    0.67                  5               74               6
3                    0.55                  5               75              15

Station
Pollutant Carbon monoxide
1                     1.2
2                    0.66
3                    0.61

[3 rows x 33 columns]

In [ ]:
# Convert the "Date_Column" to the datetime data type
ds['Date'] = pd.to_datetime(ds['Date'], format='%d-%m-%y')

# After running this, the "Date_Column" will be converted to the datetime data type.

<ipython-input-19-66a75a9a04f1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['Date'] = pd.to_datetime(ds['Date'], format='%d-%m-%y')

In [ ]:
# Format the date as 'Mon YYYY' and create a new column with the long date format
# ds['Date'] = ds['Date'].dt.strftime('%b %Y')

In [ ]:
ds.head(3)

Station         Date London Bexley                                   \
Pollutant                    Ozone Nitrogen dioxide Sulphur dioxide
1         2002-01-01             6               65               5
2         2002-01-02             5               57              21
3         2002-01-03             7               57              32

Station                   London Bloomsbury                                   \
Pollutant Carbon monoxide             Ozone Nitrogen dioxide Sulphur dioxide
1                     1.2                 7               62              18
2                    0.62                 6               59              13
3                    0.31                 5               58              28

Station                   London Brent  ... London N. Kensington  \
Pollutant Carbon monoxide        Ozone  ...      Sulphur dioxide
1                     1.1            3  ...                   13
2                     1.1            4  ...                    8
3                    0.77            2  ...                   17

Station                   London Southwark                                   \
Pollutant Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
1                     1.1                4               87              12
2                    0.57                5               70              10
3                     0.4                4               68              20

Station                   London Westminster                                   \
Pollutant Carbon monoxide              Ozone Nitrogen dioxide Sulphur dioxide
1                     1.4                  6               85               7
2                    0.67                  5               74               6
3                    0.55                  5               75              15

Station
Pollutant Carbon monoxide
1                     1.2
2                    0.66
3                    0.61

[3 rows x 33 columns]

In [ ]:
# Assuming you already have a DataFrame called df
ds.set_index("Date", inplace=True)

In [ ]:
ds.tail(2)

Station    London Bexley                                                   \
Pollutant          Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31            64               10               3            0.11
2007-01-01            61               14               3            0.16

Station    London Bloomsbury                                                   \
Pollutant              Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31                48               22               3            0.21
2007-01-01                41               48         No data            0.21

Station    London Brent                   ... London N. Kensington  \
Pollutant         Ozone Nitrogen dioxide  ...      Sulphur dioxide
Date                                      ...
2006-12-31           59               14  ...                    3
2007-01-01           62               17  ...                    3

Station                    London Southwark                                   \
Pollutant  Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
Date
2006-12-31            0.23               50               18               3
2007-01-01            0.24               46               25               1

Station                    London Westminster                   \
Pollutant  Carbon monoxide              Ozone Nitrogen dioxide
Date
2006-12-31            0.26                 58               25
2007-01-01            0.24                 48          No data

Station
Pollutant  Sulphur dioxide Carbon monoxide
Date
2006-12-31               3            0.14
2007-01-01               1            0.23

[2 rows x 32 columns]

In [ ]:
ds.replace("No data", 0, inplace=True)

<ipython-input-24-b87eb5955827>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.replace("No data", 0, inplace=True)

In [ ]:
ds.tail(2)

Station    London Bexley                                                   \
Pollutant          Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31            64               10               3            0.11
2007-01-01            61               14               3            0.16

Station    London Bloomsbury                                                   \
Pollutant              Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31                48               22               3            0.21
2007-01-01                41               48               0            0.21

Station    London Brent                   ... London N. Kensington  \
Pollutant         Ozone Nitrogen dioxide  ...      Sulphur dioxide
Date                                      ...
2006-12-31           59               14  ...                    3
2007-01-01           62               17  ...                    3

Station                    London Southwark                                   \
Pollutant  Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
Date
2006-12-31            0.23               50               18               3
2007-01-01            0.24               46               25               1

Station                    London Westminster                   \
Pollutant  Carbon monoxide              Ozone Nitrogen dioxide
Date
2006-12-31            0.26                 58               25
2007-01-01            0.24                 48                0

Station
Pollutant  Sulphur dioxide Carbon monoxide
Date
2006-12-31               3            0.14
2007-01-01               1            0.23

[2 rows x 32 columns]

In [ ]:
ds = ds.astype(float)

In [ ]:
ds['month'] = ds.index.strftime('%b %Y')

In [ ]:
ds.tail(2)

Station    London Bexley                                                   \
Pollutant          Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31          64.0             10.0             3.0            0.11
2007-01-01          61.0             14.0             3.0            0.16

Station    London Bloomsbury                                                   \
Pollutant              Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31              48.0             22.0             3.0            0.21
2007-01-01              41.0             48.0             0.0            0.21

Station    London Brent                   ... London N. Kensington  \
Pollutant         Ozone Nitrogen dioxide  ...      Carbon monoxide
Date                                      ...
2006-12-31         59.0             14.0  ...                 0.23
2007-01-01         62.0             17.0  ...                 0.24

Station    London Southwark                                                   \
Pollutant             Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
Date
2006-12-31             50.0             18.0             3.0            0.26
2007-01-01             46.0             25.0             1.0            0.24

Station    London Westminster                                   \
Pollutant               Ozone Nitrogen dioxide Sulphur dioxide
Date
2006-12-31               58.0             25.0             3.0
2007-01-01               48.0              0.0             1.0

Station                        month
Pollutant  Carbon monoxide
Date
2006-12-31            0.14  Dec 2006
2007-01-01            0.23  Jan 2007

[2 rows x 33 columns]

In [ ]:
# Group the DataFrame by the 'month' column and calculate the mean for each group
final = ds.groupby(by=["month"]).mean()

In [ ]:
# Convert the index to datetime format
final.index = pd.to_datetime(final.index, format='%b %Y')

# Sort the DataFrame based on the datetime index
k = final.sort_index()

In [ ]:
k

Station    London Bexley                                                   \
Pollutant          Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
month
2002-01-01     22.903226        32.580645        5.548387        0.399355
2002-02-01     41.285714        24.071429        0.000000        0.260000
2002-03-01     38.935484        39.967742        8.483871        0.374839
2002-04-01     55.300000        32.333333        4.900000        0.258333
2002-05-01     58.387097        24.225806        4.838710        0.227097
...                  ...              ...             ...             ...
2006-09-01     35.800000        34.400000        3.500000        0.204000
2006-10-01     29.548387        35.935484        3.838710        0.249355
2006-11-01     29.833333        46.033333        3.633333        0.332667
2006-12-01     23.548387        37.225806        4.258065        0.352581
2007-01-01     61.000000        14.000000        3.000000        0.160000

Station    London Bloomsbury                                                   \
Pollutant              Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
month
2002-01-01         17.548387        43.612903        9.741935        0.637419
2002-02-01          4.678571         3.321429        0.500000        0.031786
2002-03-01         22.064516         0.000000        5.258065        0.294581
2002-04-01         29.233333         0.000000        5.966667        0.231600
2002-05-01         37.935484         0.000000        6.387097        0.236355
...                      ...              ...             ...             ...
2006-09-01         24.433333        52.833333        3.000000        0.252333
2006-10-01         19.612903        51.000000        3.645161        0.314839
2006-11-01         18.433333        60.633333        3.666667        0.497000
2006-12-01         23.419355        53.903226        4.451613        0.554516
2007-01-01         41.000000        48.000000        0.000000        0.210000

Station    London Brent                   ... London N. Kensington  \
Pollutant         Ozone Nitrogen dioxide  ...      Sulphur dioxide
month                                     ...
2002-01-01    20.903226        40.290323  ...             4.580645
2002-02-01    29.750000        18.285714  ...             3.142857
2002-03-01    37.000000        30.354839  ...             5.483871
2002-04-01    52.133333        20.900000  ...             4.366667
2002-05-01    57.677419        17.516129  ...             3.870968
...                 ...              ...  ...                  ...
2006-09-01    40.300000        29.733333  ...             3.233333
2006-10-01    30.193548        32.870968  ...             2.903226
2006-11-01    28.200000        41.733333  ...             6.066667
2006-12-01    31.064516        38.548387  ...             4.387097
2007-01-01    62.000000        17.000000  ...             3.000000

Station                    London Southwark                                   \
Pollutant  Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
month
2002-01-01        0.362903        21.870968        51.903226        7.000000
2002-02-01        0.157500        38.035714        43.428571        4.750000
2002-03-01        0.332903        30.741935        53.612903        6.806452
2002-04-01        0.298667        50.333333        51.400000        3.800000
2002-05-01        0.339355        55.290323        41.806452        4.193548
...                    ...              ...              ...             ...
2006-09-01        0.218667        30.266667        34.166667        2.900000
2006-10-01        0.257097        21.387097        39.193548        3.419355
2006-11-01        0.415000        21.033333        50.666667        4.133333
2006-12-01        0.404839        26.709677        47.387097        2.677419
2007-01-01        0.240000        46.000000        25.000000        1.000000

Station                    London Westminster                   \
Pollutant  Carbon monoxide              Ozone Nitrogen dioxide
month
2002-01-01        0.578387          22.290323        54.161290
2002-02-01        0.419643          24.964286        34.750000
2002-03-01        0.422581          29.258065        53.709677
2002-04-01        0.417667          45.300000        47.466667
2002-05-01        0.340323          47.000000        35.419355
...                    ...                ...              ...
2006-09-01        0.339667          30.700000        38.600000
2006-10-01        0.316774          27.032258        44.387097
2006-11-01        0.470667          25.866667        50.900000
2006-12-01        0.492903          30.161290        45.354839
2007-01-01        0.240000          48.000000         0.000000

Station
Pollutant  Sulphur dioxide Carbon monoxide
month
2002-01-01        4.387097        0.604194
2002-02-01        3.678571        0.436071
2002-03-01        5.064516        0.522581
2002-04-01        2.233333        0.517333
2002-05-01        3.419355        0.370645
...                    ...             ...
2006-09-01        3.733333        0.099667
2006-10-01        2.806452        0.268065
2006-11-01        4.666667        0.284667
2006-12-01        6.129032        0.304516
2007-01-01        1.000000        0.230000

[61 rows x 32 columns]

In [ ]:
k.index = k.index.strftime('%b %Y')

In [ ]:
k

Station   London Bexley                                                   \
Pollutant         Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
month
Jan 2002      22.903226        32.580645        5.548387        0.399355
Feb 2002      41.285714        24.071429        0.000000        0.260000
Mar 2002      38.935484        39.967742        8.483871        0.374839
Apr 2002      55.300000        32.333333        4.900000        0.258333
May 2002      58.387097        24.225806        4.838710        0.227097
...                 ...              ...             ...             ...
Sep 2006      35.800000        34.400000        3.500000        0.204000
Oct 2006      29.548387        35.935484        3.838710        0.249355
Nov 2006      29.833333        46.033333        3.633333        0.332667
Dec 2006      23.548387        37.225806        4.258065        0.352581
Jan 2007      61.000000        14.000000        3.000000        0.160000

Station   London Bloomsbury                                                   \
Pollutant             Ozone Nitrogen dioxide Sulphur dioxide Carbon monoxide
month
Jan 2002          17.548387        43.612903        9.741935        0.637419
Feb 2002           4.678571         3.321429        0.500000        0.031786
Mar 2002          22.064516         0.000000        5.258065        0.294581
Apr 2002          29.233333         0.000000        5.966667        0.231600
May 2002          37.935484         0.000000        6.387097        0.236355
...                     ...              ...             ...             ...
Sep 2006          24.433333        52.833333        3.000000        0.252333
Oct 2006          19.612903        51.000000        3.645161        0.314839
Nov 2006          18.433333        60.633333        3.666667        0.497000
Dec 2006          23.419355        53.903226        4.451613        0.554516
Jan 2007          41.000000        48.000000        0.000000        0.210000

Station   London Brent                   ... London N. Kensington  \
Pollutant        Ozone Nitrogen dioxide  ...      Sulphur dioxide
month                                    ...
Jan 2002     20.903226        40.290323  ...             4.580645
Feb 2002     29.750000        18.285714  ...             3.142857
Mar 2002     37.000000        30.354839  ...             5.483871
Apr 2002     52.133333        20.900000  ...             4.366667
May 2002     57.677419        17.516129  ...             3.870968
...                ...              ...  ...                  ...
Sep 2006     40.300000        29.733333  ...             3.233333
Oct 2006     30.193548        32.870968  ...             2.903226
Nov 2006     28.200000        41.733333  ...             6.066667
Dec 2006     31.064516        38.548387  ...             4.387097
Jan 2007     62.000000        17.000000  ...             3.000000

Station                   London Southwark                                   \
Pollutant Carbon monoxide            Ozone Nitrogen dioxide Sulphur dioxide
month
Jan 2002         0.362903        21.870968        51.903226        7.000000
Feb 2002         0.157500        38.035714        43.428571        4.750000
Mar 2002         0.332903        30.741935        53.612903        6.806452
Apr 2002         0.298667        50.333333        51.400000        3.800000
May 2002         0.339355        55.290323        41.806452        4.193548
...                   ...              ...              ...             ...
Sep 2006         0.218667        30.266667        34.166667        2.900000
Oct 2006         0.257097        21.387097        39.193548        3.419355
Nov 2006         0.415000        21.033333        50.666667        4.133333
Dec 2006         0.404839        26.709677        47.387097        2.677419
Jan 2007         0.240000        46.000000        25.000000        1.000000

Station                   London Westminster                                   \
Pollutant Carbon monoxide              Ozone Nitrogen dioxide Sulphur dioxide
month
Jan 2002         0.578387          22.290323        54.161290        4.387097
Feb 2002         0.419643          24.964286        34.750000        3.678571
Mar 2002         0.422581          29.258065        53.709677        5.064516
Apr 2002         0.417667          45.300000        47.466667        2.233333
May 2002         0.340323          47.000000        35.419355        3.419355
...                   ...                ...              ...             ...
Sep 2006         0.339667          30.700000        38.600000        3.733333
Oct 2006         0.316774          27.032258        44.387097        2.806452
Nov 2006         0.470667          25.866667        50.900000        4.666667
Dec 2006         0.492903          30.161290        45.354839        6.129032
Jan 2007         0.240000          48.000000         0.000000        1.000000

Station
Pollutant Carbon monoxide
month
Jan 2002         0.604194
Feb 2002         0.436071
Mar 2002         0.522581
Apr 2002         0.517333
May 2002         0.370645
...                   ...
Sep 2006         0.099667
Oct 2006         0.268065
Nov 2006         0.284667
Dec 2006         0.304516
Jan 2007         0.230000

[61 rows x 32 columns]

In [ ]:
k.T

month                                     Jan 2002   Feb 2002   Mar 2002  \
Station                Pollutant
London Bexley          Ozone             22.903226  41.285714  38.935484
                       Nitrogen dioxide  32.580645  24.071429  39.967742
                       Sulphur dioxide    5.548387   0.000000   8.483871
                       Carbon monoxide    0.399355   0.260000   0.374839
London Bloomsbury      Ozone             17.548387   4.678571  22.064516
                       Nitrogen dioxide  43.612903   3.321429   0.000000
                       Sulphur dioxide    9.741935   0.500000   5.258065
                       Carbon monoxide    0.637419   0.031786   0.294581
London Brent           Ozone             20.903226  29.750000  37.000000
                       Nitrogen dioxide  40.290323  18.285714  30.354839
                       Sulphur dioxide    5.677419   2.035714   4.419355
                       Carbon monoxide    0.324268   0.102146   0.184032
London Hillingdon      Ozone             15.225806  33.714286  24.161290
                       Nitrogen dioxide  45.870968  39.714286  54.064516
                       Sulphur dioxide    5.387097   6.071429   7.645161
                       Carbon monoxide    0.656452   0.500000   0.523548
London Marylebone Road Ozone              7.419355  14.857143  14.967742
                       Nitrogen dioxide  79.161290  72.000000  82.580645
                       Sulphur dioxide   14.548387   8.178571  10.870968
                       Carbon monoxide    1.612258   1.184643   1.123548
London N. Kensington   Ozone             21.612903  40.821429  34.290323
                       Nitrogen dioxide  36.774194  30.035714  47.354839
                       Sulphur dioxide    4.580645   3.142857   5.483871
                       Carbon monoxide    0.362903   0.157500   0.332903
London Southwark       Ozone             21.870968  38.035714  30.741935
                       Nitrogen dioxide  51.903226  43.428571  53.612903
                       Sulphur dioxide    7.000000   4.750000   6.806452
                       Carbon monoxide    0.578387   0.419643   0.422581
London Westminster     Ozone             22.290323  24.964286  29.258065
                       Nitrogen dioxide  54.161290  34.750000  53.709677
                       Sulphur dioxide    4.387097   3.678571   5.064516
                       Carbon monoxide    0.604194   0.436071   0.522581

month                                     Apr 2002   May 2002   Jun 2002  \
Station                Pollutant
London Bexley          Ozone             55.300000  58.387097  49.100000
                       Nitrogen dioxide  32.333333  24.225806  20.200000
                       Sulphur dioxide    4.900000   4.838710   5.400000
                       Carbon monoxide    0.258333   0.227097   0.269000
London Bloomsbury      Ozone             29.233333  37.935484  32.433333
                       Nitrogen dioxide   0.000000   0.000000   0.000000
                       Sulphur dioxide    5.966667   6.387097   4.900000
                       Carbon monoxide    0.231600   0.236355   0.175700
London Brent           Ozone             52.133333  57.677419  46.566667
                       Nitrogen dioxide  20.900000  17.516129  17.100000
                       Sulphur dioxide    2.100000   3.225806   2.666667
                       Carbon monoxide    0.177567   0.073823   0.061710
London Hillingdon      Ozone             41.400000  35.709677  25.500000
                       Nitrogen dioxide  47.366667  48.580645  33.500000
                       Sulphur dioxide    5.433333   5.000000   6.400000
                       Carbon monoxide    0.469333   0.216774   0.000000
London Marylebone Road Ozone             27.833333  22.548387  15.300000
                       Nitrogen dioxide  80.000000  84.096774  81.766667
                       Sulphur dioxide    7.933333   7.645161   7.733333
                       Carbon monoxide    1.016333   1.424839   1.648000
London N. Kensington   Ozone             50.833333  51.967742  42.466667
                       Nitrogen dioxide  39.666667  33.225806  30.700000
                       Sulphur dioxide    4.366667   3.870968   2.666667
                       Carbon monoxide    0.298667   0.339355   0.222333
London Southwark       Ozone             50.333333  55.290323  46.066667
                       Nitrogen dioxide  51.400000  41.806452  40.233333
                       Sulphur dioxide    3.800000   4.193548   4.200000
                       Carbon monoxide    0.417667   0.340323   0.350667
London Westminster     Ozone             45.300000  47.000000  40.666667
                       Nitrogen dioxide  47.466667  35.419355  27.266667
                       Sulphur dioxide    2.233333   3.419355   2.800000
                       Carbon monoxide    0.517333   0.370645   0.321667

month                                     Jul 2002   Aug 2002   Sep 2002  \
Station                Pollutant
London Bexley          Ozone             38.580645  32.709677  38.666667
                       Nitrogen dioxide  24.612903  16.225806  17.500000
                       Sulphur dioxide    8.741935   6.225806   7.166667
                       Carbon monoxide    0.199677   0.070645   0.341000
London Bloomsbury      Ozone             21.806452  20.612903  20.366667
                       Nitrogen dioxide   0.000000   0.000000   0.000000
                       Sulphur dioxide    6.000000   4.419355   7.200000
                       Carbon monoxide    0.167968   0.260645   0.302233
London Brent           Ozone             41.258065  35.580645  35.400000
                       Nitrogen dioxide  22.193548  24.161290  25.733333
                       Sulphur dioxide    2.806452   1.935484   2.933333
                       Carbon monoxide    0.054242   0.119742   0.241900
London Hillingdon      Ozone             28.935484  26.709677  27.233333
                       Nitrogen dioxide  34.225806  33.290323  36.966667
                       Sulphur dioxide    8.935484   7.516129   6.933333
                       Carbon monoxide    0.383548   0.369677   0.389667
London Marylebone Road Ozone             18.161290  16.645161  21.266667
                       Nitrogen dioxide  75.516129  71.225806  71.533333
                       Sulphur dioxide   10.612903   8.451613   7.966667
                       Carbon monoxide    1.536774   1.348065   1.228667
London N. Kensington   Ozone             36.741935  30.870968  32.533333
                       Nitrogen dioxide  32.580645  36.225806  40.366667
                       Sulphur dioxide    4.580645   3.451613   4.333333
                       Carbon monoxide    0.284194   0.477742   0.381067
London Southwark       Ozone             32.645161  28.645161  31.133333
                       Nitrogen dioxide  40.903226  43.096774  34.033333
                       Sulphur dioxide    6.354839   7.580645   6.566667
                       Carbon monoxide    0.282258   0.308065   0.270000
London Westminster     Ozone             36.225806  30.677419  28.633333
                       Nitrogen dioxide  33.096774  33.580645  48.366667
                       Sulphur dioxide    4.258065   3.516129   2.733333
                       Carbon monoxide    0.169032   0.358710   0.524667

month                                     Oct 2002  ...   Apr 2006  \
Station                Pollutant                    ...
London Bexley          Ozone             23.612903  ...  55.333333
                       Nitrogen dioxide  41.064516  ...  32.833333
                       Sulphur dioxide    9.741935  ...   3.833333
                       Carbon monoxide    0.426452  ...   0.178667
London Bloomsbury      Ozone             13.612903  ...  34.266667
                       Nitrogen dioxide   0.000000  ...  62.266667
                       Sulphur dioxide   10.096774  ...   5.366667
                       Carbon monoxide    0.372581  ...   0.506333
London Brent           Ozone             22.419355  ...  50.833333
                       Nitrogen dioxide  43.741935  ...  25.100000
                       Sulphur dioxide    5.064516  ...   2.200000
                       Carbon monoxide    0.460742  ...   0.176000
London Hillingdon      Ozone             17.000000  ...  39.566667
                       Nitrogen dioxide  50.096774  ...  40.700000
                       Sulphur dioxide    7.612903  ...   2.133333
                       Carbon monoxide    0.598387  ...   0.367000
London Marylebone Road Ozone              6.838710  ...  19.033333
                       Nitrogen dioxide  80.709677  ...  88.466667
                       Sulphur dioxide   11.451613  ...   5.666667
                       Carbon monoxide    1.535484  ...   0.000000
London N. Kensington   Ozone             17.935484  ...  23.266667
                       Nitrogen dioxide  47.645161  ...  35.633333
                       Sulphur dioxide    5.387097  ...   3.166667
                       Carbon monoxide    0.523226  ...   0.253667
London Southwark       Ozone             17.645161  ...   0.000000
                       Nitrogen dioxide  39.935484  ...  44.766667
                       Sulphur dioxide    5.387097  ...   4.133333
                       Carbon monoxide    0.331613  ...   0.343333
London Westminster     Ozone             17.322581  ...  42.833333
                       Nitrogen dioxide  47.451613  ...  45.400000
                       Sulphur dioxide    4.483871  ...   3.733333
                       Carbon monoxide    0.658710  ...   0.000000

month                                      May 2006    Jun 2006    Jul 2006  \
Station                Pollutant
London Bexley          Ozone              53.354839   57.500000   51.451613
                       Nitrogen dioxide   31.806452   35.300000   26.354839
                       Sulphur dioxide     4.677419    8.533333    5.967742
                       Carbon monoxide     0.190323    0.172667    0.174839
London Bloomsbury      Ozone              31.096774   42.333333   52.580645
                       Nitrogen dioxide   42.451613   52.266667   54.064516
                       Sulphur dioxide     3.129032    4.033333    6.548387
                       Carbon monoxide     0.251290    0.212667    0.236129
London Brent           Ozone              56.290323   62.766667   73.677419
                       Nitrogen dioxide   21.064516   21.933333   20.967742
                       Sulphur dioxide     1.225806    3.800000    3.709677
                       Carbon monoxide     0.164194    0.129667    0.156774
London Hillingdon      Ozone              33.258065   41.766667   39.161290
                       Nitrogen dioxide   50.451613   50.933333   37.709677
                       Sulphur dioxide     2.258065    3.166667    3.387097
                       Carbon monoxide     0.386129    0.332000    0.306129
London Marylebone Road Ozone              19.903226   26.733333   25.193548
                       Nitrogen dioxide  106.903226  110.333333  116.645161
                       Sulphur dioxide     6.290323    3.900000   12.870968
                       Carbon monoxide     1.028710    1.065667    0.945161
London N. Kensington   Ozone              52.935484   62.600000   70.870968
                       Nitrogen dioxide   30.677419   33.866667   33.032258
                       Sulphur dioxide     2.903226    2.733333    5.419355
                       Carbon monoxide     0.197742    0.181000    0.223548
London Southwark       Ozone               0.000000    0.000000    0.000000
                       Nitrogen dioxide   39.354839   37.366667   35.516129
                       Sulphur dioxide     4.838710    5.266667    7.580645
                       Carbon monoxide     0.342903    0.332000    0.219677
London Westminster     Ozone              42.774194   58.100000   62.258065
                       Nitrogen dioxide   33.838710   44.333333   52.354839
                       Sulphur dioxide     2.419355    2.900000    5.677419
                       Carbon monoxide     0.000000    0.000000    0.000000

month                                     Aug 2006    Sep 2006    Oct 2006  \
Station                Pollutant
London Bexley          Ozone             37.032258   35.800000   29.548387
                       Nitrogen dioxide  13.548387   34.400000   35.935484
                       Sulphur dioxide    3.096774    3.500000    3.838710
                       Carbon monoxide    0.182258    0.204000    0.249355
London Bloomsbury      Ozone             23.258065   24.433333   19.612903
                       Nitrogen dioxide  50.161290   52.833333   51.000000
                       Sulphur dioxide    2.806452    3.000000    3.645161
                       Carbon monoxide    0.186129    0.252333    0.314839
London Brent           Ozone             41.967742   40.300000   30.193548
                       Nitrogen dioxide  19.709677   29.733333   32.870968
                       Sulphur dioxide    0.645161    3.133333    3.451613
                       Carbon monoxide    0.160645    0.203333    0.264194
London Hillingdon      Ozone             25.838710   18.033333   15.129032
                       Nitrogen dioxide  28.193548   53.200000   51.548387
                       Sulphur dioxide    1.419355    0.833333    2.193548
                       Carbon monoxide    0.408710    0.451333    0.499032
London Marylebone Road Ozone             16.354839    9.533333    8.516129
                       Nitrogen dioxide  75.677419  112.166667  121.483871
                       Sulphur dioxide    6.935484    5.566667    7.612903
                       Carbon monoxide    0.000000    0.000000    0.387097
London N. Kensington   Ozone             37.516129   33.600000   27.870968
                       Nitrogen dioxide  28.483871   36.833333   36.064516
                       Sulphur dioxide    2.000000    3.233333    2.903226
                       Carbon monoxide    0.225161    0.218667    0.257097
London Southwark       Ozone             26.774194   30.266667   21.387097
                       Nitrogen dioxide  36.709677   34.166667   39.193548
                       Sulphur dioxide    1.645161    2.900000    3.419355
                       Carbon monoxide    0.389355    0.339667    0.316774
London Westminster     Ozone             32.258065   30.700000   27.032258
                       Nitrogen dioxide  53.000000   38.600000   44.387097
                       Sulphur dioxide    3.580645    3.733333    2.806452
                       Carbon monoxide    0.000000    0.099667    0.268065

month                                      Nov 2006    Dec 2006  Jan 2007
Station                Pollutant
London Bexley          Ozone              29.833333   23.548387     61.00
                       Nitrogen dioxide   46.033333   37.225806     14.00
                       Sulphur dioxide     3.633333    4.258065      3.00
                       Carbon monoxide     0.332667    0.352581      0.16
London Bloomsbury      Ozone              18.433333   23.419355     41.00
                       Nitrogen dioxide   60.633333   53.903226     48.00
                       Sulphur dioxide     3.666667    4.451613      0.00
                       Carbon monoxide     0.497000    0.554516      0.21
London Brent           Ozone              28.200000   31.064516     62.00
                       Nitrogen dioxide   41.733333   38.548387     17.00
                       Sulphur dioxide     3.400000    3.322581      3.00
                       Carbon monoxide     0.326667    0.285484      0.20
London Hillingdon      Ozone              15.300000   20.709677     48.00
                       Nitrogen dioxide   57.900000   50.322581     23.00
                       Sulphur dioxide     1.933333    2.096774      0.00
                       Carbon monoxide     0.599667    0.515484      0.25
London Marylebone Road Ozone               6.766667    9.677419     18.00
                       Nitrogen dioxide  136.900000  121.451613     99.00
                       Sulphur dioxide     9.466667    7.677419      4.00
                       Carbon monoxide     0.915667    0.982258      1.00
London N. Kensington   Ozone              25.633333   29.225806     56.00
                       Nitrogen dioxide   46.566667   42.096774     16.00
                       Sulphur dioxide     6.066667    4.387097      3.00
                       Carbon monoxide     0.415000    0.404839      0.24
London Southwark       Ozone              21.033333   26.709677     46.00
                       Nitrogen dioxide   50.666667   47.387097     25.00
                       Sulphur dioxide     4.133333    2.677419      1.00
                       Carbon monoxide     0.470667    0.492903      0.24
London Westminster     Ozone              25.866667   30.161290     48.00
                       Nitrogen dioxide   50.900000   45.354839      0.00
                       Sulphur dioxide     4.666667    6.129032      1.00
                       Carbon monoxide     0.284667    0.304516      0.23

[32 rows x 61 columns]

In [ ]:
# Assuming your DataFrame is named 'df' and you want to save it to 'output.csv'
k.T.to_csv('output.csv')  # Use index=False to exclude row indices in the output